DECLARE
  v_seq_exists INTEGER;
  v_max_id     INTEGER;
  v_start      INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_seq_exists
  FROM user_sequences
  WHERE sequence_name = 'SEQ_T_MT_FUNCIONARIO';

  IF v_seq_exists = 0 THEN
    SELECT NVL(MAX(ID_FUNCIONARIO),0) INTO v_max_id FROM T_MT_FUNCIONARIO;
    v_start := v_max_id + 1;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_T_MT_FUNCIONARIO START WITH '||v_start||' INCREMENT BY 1';
  END IF;
END;
/
-- 2. Garantir trigger
DECLARE
  v_trg_exists INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_trg_exists
  FROM user_triggers
  WHERE trigger_name = 'TRG_T_MT_FUNCIONARIO_BI';

  IF v_trg_exists = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE OR REPLACE TRIGGER TRG_T_MT_FUNCIONARIO_BI
      BEFORE INSERT ON T_MT_FUNCIONARIO
      FOR EACH ROW
      BEGIN
        IF :NEW.ID_FUNCIONARIO IS NULL THEN
          SELECT SEQ_T_MT_FUNCIONARIO.NEXTVAL INTO :NEW.ID_FUNCIONARIO FROM dual;
        END IF;
      END;
    ]';
  END IF;
END;
/
-- 3. Seeds idempotentes
DECLARE
  v_count INTEGER;
  v_id_role_admin NUMBER;
  v_id_role_user  NUMBER;
  v_func_admin    NUMBER;
  v_func_user     NUMBER;
BEGIN
  -- Endereço base (caso não exista)
  SELECT COUNT(*) INTO v_count FROM T_MT_ENDERECO WHERE NR_CEP = 20140702;
  IF v_count = 0 THEN
    INSERT INTO T_MT_ENDERECO (NR_CEP, ID_PAIS, SG_ESTADO, ID_CIDADE, ID_BAIRRO, NR_NUMERO, DS_LOGRADOURO, DS_COMPLEMENTO)
    VALUES (20140702, 'Brasil', 'SP', 'São Paulo', 'Centro', 100, 'Av. Principal', 'Apto 101');
  END IF;

  -- Segundo CEP
  SELECT COUNT(*) INTO v_count FROM T_MT_ENDERECO WHERE NR_CEP = 40010000;
  IF v_count = 0 THEN
    INSERT INTO T_MT_ENDERECO (NR_CEP, ID_PAIS, SG_ESTADO, ID_CIDADE, ID_BAIRRO, NR_NUMERO, DS_LOGRADOURO)
    VALUES (40010000, 'Brasil', 'RJ', 'Rio de Janeiro', 'Centro', 50, 'Rua Central');
  END IF;

  -- Moto
  SELECT COUNT(*) INTO v_count FROM T_MT_MOTO WHERE CD_PLACA = 'ABC1234';
  IF v_count = 0 THEN
    INSERT INTO T_MT_MOTO (CD_PLACA, CD_CPF, CD_NIV, CD_MOTOR, CD_RENAVAM, CD_FIPE)
    VALUES ('ABC1234', '12345678909', '9BWZZZ377VT004251', 'CG123456', 12345678, 9200);
  END IF;

  -- Usuário
  SELECT COUNT(*) INTO v_count FROM T_MT_USUARIO WHERE CD_CPF = '12345678909';
  IF v_count = 0 THEN
    INSERT INTO T_MT_USUARIO (CD_CPF, NR_CEP, CD_PLACA, DT_NASCIMENTO, ID_NOME)
    VALUES ('12345678909', 20140702, 'ABC1234', DATE '1990-05-20', 'João da Silva');
  END IF;

  -- Roles
  SELECT COUNT(*) INTO v_count FROM T_MT_ROLE WHERE NM_ROLE='ROLE_ADMIN';
  IF v_count = 0 THEN
    INSERT INTO T_MT_ROLE (NM_ROLE) VALUES ('ROLE_ADMIN');
  END IF;

  SELECT COUNT(*) INTO v_count FROM T_MT_ROLE WHERE NM_ROLE='ROLE_USER';
  IF v_count = 0 THEN
    INSERT INTO T_MT_ROLE (NM_ROLE) VALUES ('ROLE_USER');
  END IF;

  SELECT ID_ROLE INTO v_id_role_admin FROM T_MT_ROLE WHERE NM_ROLE='ROLE_ADMIN';
  SELECT ID_ROLE INTO v_id_role_user  FROM T_MT_ROLE WHERE NM_ROLE='ROLE_USER';

  -- Funcionário ADMIN
  SELECT COUNT(*) INTO v_count FROM T_MT_FUNCIONARIO WHERE CD_CPF='99999999999';
  IF v_count = 0 THEN
    INSERT INTO T_MT_FUNCIONARIO (ID_NOME, CD_CPF, CD_SENHA, NR_CEP)
    VALUES ('Administrador', '99999999999', '$2a$10$Dow1xBkAuCEi0aKBslZx2eqXr/7EQo1leChX2NDSSSXqoQZnQEqnS', 20140702);
  END IF;

  -- Funcionário USER
  SELECT COUNT(*) INTO v_count FROM T_MT_FUNCIONARIO WHERE CD_CPF='88888888888';
  IF v_count = 0 THEN
    INSERT INTO T_MT_FUNCIONARIO (ID_NOME, CD_CPF, CD_SENHA, NR_CEP)
    VALUES ('Operador', '88888888888', '$2a$10$6XyXcXwjlzAIXazhbugzu.zRMx9x6pRP70dNDO7xjMnIKh4j/wZ1e', 40010000);
  END IF;

  -- Buscar IDs
  SELECT ID_FUNCIONARIO INTO v_func_admin FROM T_MT_FUNCIONARIO WHERE CD_CPF='99999999999';
  SELECT ID_FUNCIONARIO INTO v_func_user  FROM T_MT_FUNCIONARIO WHERE CD_CPF='88888888888';

  -- Vincular roles
  SELECT COUNT(*) INTO v_count FROM T_MT_FUNCIONARIO_ROLE WHERE ID_FUNCIONARIO=v_func_admin AND ID_ROLE=v_id_role_admin;
  IF v_count = 0 THEN
    INSERT INTO T_MT_FUNCIONARIO_ROLE (ID_FUNCIONARIO, ID_ROLE) VALUES (v_func_admin, v_id_role_admin);
  END IF;

  SELECT COUNT(*) INTO v_count FROM T_MT_FUNCIONARIO_ROLE WHERE ID_FUNCIONARIO=v_func_admin AND ID_ROLE=v_id_role_user;
  IF v_count = 0 THEN
    INSERT INTO T_MT_FUNCIONARIO_ROLE (ID_FUNCIONARIO, ID_ROLE) VALUES (v_func_admin, v_id_role_user);
  END IF;

  SELECT COUNT(*) INTO v_count FROM T_MT_FUNCIONARIO_ROLE WHERE ID_FUNCIONARIO=v_func_user AND ID_ROLE=v_id_role_user;
  IF v_count = 0 THEN
    INSERT INTO T_MT_FUNCIONARIO_ROLE (ID_FUNCIONARIO, ID_ROLE) VALUES (v_func_user, v_id_role_user);
  END IF;
END;
/