DECLARE
  v_exists NUMBER;
BEGIN

  SELECT COUNT(*) INTO v_exists
  FROM user_tab_cols
  WHERE table_name = 'T_MT_FUNCIONARIO'
    AND column_name = 'DT_CRIACAO';

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE T_MT_FUNCIONARIO ADD (DT_CRIACAO DATE, DT_ATUALIZACAO DATE)';

    EXECUTE IMMEDIATE 'UPDATE T_MT_FUNCIONARIO SET DT_CRIACAO = SYSDATE, DT_ATUALIZACAO = SYSDATE';
  ELSE
 
    EXECUTE IMMEDIATE q'[
      UPDATE T_MT_FUNCIONARIO
         SET DT_CRIACAO = NVL(DT_CRIACAO, SYSDATE),
             DT_ATUALIZACAO = NVL(DT_ATUALIZACAO, SYSDATE)
    ]';
  END IF;

END;
/